# 站点基础信息
title: zchhaa | 通信与AI交叉研究
description: 通信领域硕士研究生，专注于粒子群算法、天线设计、射频技术的交叉研究与应用
url: "https://zhouh406.github.io"
baseurl: ""
author: zchhaa
email: zhouh268@mail2.sysu.edu.cn
lang: zh-CN

# 主题与扩展
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    github: zhouh406
    email: zhouh268@mail2.sysu.edu.cn
  show_footer_info: true
  show_social_links: true

# 导航栏
header_pages:
  - about.md

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

# SEO优化
seo:
  type: Person
  name: zchhaa
  description: 通信领域硕士研究生，专注于粒子群算法、天线设计、射频技术研究
  url: https://zhouh406.github.io
  image: /assets/profile.jpg
  social:
    name: zchhaa
    links:
      - https://github.com/zhouh406
      - mailto:zhouh268@mail2.sysu.edu.cn

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 构建设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
