# 站点基础信息
title: zchhaa | 通信与AI交叉研究
description: 记录粒子群算法、天线设计、通信领域的学习与思考
url: "https://zhouh406.github.io" # 替换为你的GitHub Pages实际地址
baseurl: "" # 个人主页仓库无需子路径，留空

# 主题与扩展（使用Jekyll官方Minima主题，易扩展）
remote_theme: jekyll/minima
minima:
  skin: auto # 自动适配浅色/深色模式，也可指定"dark"
  social_links: # 社交平台链接（需替换为你的账号）
    github: zhouh406
    # linkedin: your-linkedin-username
    # twitter: your-twitter-username

# 导航栏（若需额外页面，可创建about.md等并在此配置）
header_pages:
  # - about.md

# 插件（GitHub Pages默认支持，增强功能）
plugins:
  - jekyll-feed # 生成RSS订阅
  - jekyll-seo-tag # SEO优化
  - jekyll-sitemap # 站点地图
